<?xml version="1.0" encoding="utf-8"?><Database Name="DoAn" Class="KVCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BRAVO15\SQLEXPRESS;Initial Catalog=DoAn;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="DoAnConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CT_TroChoi" Member="CT_TroChois">
    <Type Name="CT_TroChoi">
      <Column Name="MaTC" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTB" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ThietBi_CT_TroChoi" Member="ThietBi" ThisKey="MaTB" OtherKey="MaTB" Type="ThietBi" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="TroChoi_CT_TroChoi" Member="TroChoi" ThisKey="MaTC" OtherKey="MaTC" Type="TroChoi" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ve_TP" Member="Ve_TPs">
    <Type Name="Ve_TP">
      <Column Name="MaCTHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="CTHD_Ve_Ve_TP" Member="CTHD_Ve" ThisKey="MaCTHD" OtherKey="MaCTHD" Type="CTHD_Ve" IsForeignKey="true" />
      <Association Name="ThucPham_Ve_TP" Member="ThucPham" ThisKey="MaTP" OtherKey="MaTP" Type="ThucPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPN_TB" Member="CTPN_TBs">
    <Type Name="CTPN_TB">
      <Column Name="MaPhieu" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTB" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaNhap" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PhieuNhap_CTPN_TB" Member="PhieuNhap" ThisKey="MaPhieu" OtherKey="MaPhieu" Type="PhieuNhap" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPN_TP" Member="CTPN_TPs">
    <Type Name="CTPN_TP">
      <Column Name="MaPhieu" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaNhap" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PhieuNhap_CTPN_TP" Member="PhieuNhap" ThisKey="MaPhieu" OtherKey="MaPhieu" Type="PhieuNhap" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTHD_TP" Member="CTHD_TPs">
    <Type Name="CTHD_TP">
      <Column Name="MaHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="HoaDon_CTHD_TP" Member="HoaDon" ThisKey="MaHD" OtherKey="MaHD" Type="HoaDon" IsForeignKey="true" />
      <Association Name="ThucPham_CTHD_TP" Member="ThucPham" ThisKey="MaTP" OtherKey="MaTP" Type="ThucPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTHD_Ve" Member="CTHD_Ves">
    <Type Name="CTHD_Ve">
      <Column Name="MaCTHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHD" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaVe" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoNguoiLon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTreEm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="CTHD_Ve_Ve_TP" Member="Ve_TPs" ThisKey="MaCTHD" OtherKey="MaCTHD" Type="Ve_TP" />
      <Association Name="HoaDon_CTHD_Ve" Member="HoaDon" ThisKey="MaHD" OtherKey="MaHD" Type="HoaDon" IsForeignKey="true" />
      <Association Name="NhanVien_CTHD_Ve" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
      <Association Name="Ve_CTHD_Ve" Member="Ve" ThisKey="MaVe" OtherKey="MaVe" Type="Ve" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="MaHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaKM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayIn" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="HoaDon_CTHD_TP" Member="CTHD_TPs" ThisKey="MaHD" OtherKey="MaHD" Type="CTHD_TP" />
      <Association Name="HoaDon_CTHD_Ve" Member="CTHD_Ves" ThisKey="MaHD" OtherKey="MaHD" Type="CTHD_Ve" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="KhuyenMai_HoaDon" Member="KhuyenMai" ThisKey="MaKM" OtherKey="MaKM" Type="KhuyenMai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Diem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoaiKH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoTreEm" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="MaKH" OtherKey="MaKH" Type="HoaDon" />
      <Association Name="LoaiKH_KhachHang" Member="LoaiKH1" ThisKey="LoaiKH" OtherKey="MaLoai" Type="LoaiKH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhuyenMai" Member="KhuyenMais">
    <Type Name="KhuyenMai">
      <Column Name="MaKM" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKM" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PhanTramGiam" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="KhuyenMai_HoaDon" Member="HoaDons" ThisKey="MaKM" OtherKey="MaKM" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.LichLamViec" Member="LichLamViecs">
    <Type Name="LichLamViec">
      <Column Name="MaLich" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ca" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianLam" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="LichLamViec_TKB" Member="TKBs" ThisKey="MaLich" OtherKey="MaLich" Type="TKB" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiKH" Member="LoaiKHs">
    <Type Name="LoaiKH">
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDiemCanThangLoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoaiKH_KhachHang" Member="KhachHangs" ThisKey="MaLoai" OtherKey="LoaiKH" Type="KhachHang" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiNV" Member="LoaiNVs">
    <Type Name="LoaiNV">
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HeSoLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LuongCB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="LoaiNV_NhanVien" Member="NhanViens" ThisKey="MaLoai" OtherKey="LoaiNV" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTC" Member="LoaiTCs">
    <Type Name="LoaiTC">
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiTC_TroChoi" Member="TroChois" ThisKey="MaLoai" OtherKey="LoaiTroChoi" Type="TroChoi" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTP" Member="LoaiTPs">
    <Type Name="LoaiTP">
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiTP_ThucPham" Member="ThucPhams" ThisKey="MaLoai" OtherKey="MaLoai" Type="ThucPham" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiVe" Member="LoaiVes">
    <Type Name="LoaiVe">
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GiaTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="LoaiVe_Ve" Member="Ves" ThisKey="MaLoai" OtherKey="LoaiVe" Type="Ve" />
    </Type>
  </Table>
  <Table Name="dbo.ManHinh" Member="ManHinhs">
    <Type Name="ManHinh">
      <Column Name="MaMH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="ManHinh_PhanQuyen" Member="PhanQuyens" ThisKey="MaMH" OtherKey="MaMH" Type="PhanQuyen" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LoaiNCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhaCungCap_NhaCungCap_DanhSachSP" Member="NhaCungCap_DanhSachSPs" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap_DanhSachSP" />
      <Association Name="NhaCungCap_PhieuNhap" Member="PhieuNhaps" ThisKey="MaNCC" OtherKey="MaNCC" Type="PhieuNhap" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap_DanhSachSP" Member="NhaCungCap_DanhSachSPs">
    <Type Name="NhaCungCap_DanhSachSP">
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="NhaCungCap_NhaCungCap_DanhSachSP" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="LoaiNV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="NhanVien_CTHD_Ve" Member="CTHD_Ves" ThisKey="MaNV" OtherKey="MaNV" Type="CTHD_Ve" />
      <Association Name="NhanVien_PhieuNhap" Member="PhieuNhaps" ThisKey="MaNV" OtherKey="MaNV" Type="PhieuNhap" />
      <Association Name="NhanVien_TaiKhoan" Member="TaiKhoans" ThisKey="MaNV" OtherKey="MaNV" Type="TaiKhoan" />
      <Association Name="NhanVien_TKB" Member="TKBs" ThisKey="MaNV" OtherKey="MaNV" Type="TKB" />
      <Association Name="LoaiNV_NhanVien" Member="LoaiNV1" ThisKey="LoaiNV" OtherKey="MaLoai" Type="LoaiNV" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanQuyen" Member="PhanQuyens">
    <Type Name="PhanQuyen">
      <Column Name="MaVaiTro" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaMH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoatDong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ManHinh_PhanQuyen" Member="ManHinh" ThisKey="MaMH" OtherKey="MaMH" Type="ManHinh" IsForeignKey="true" />
      <Association Name="VaiTro_PhanQuyen" Member="VaiTro" ThisKey="MaVaiTro" OtherKey="MaVaiTro" Type="VaiTro" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhap" Member="PhieuNhaps">
    <Type Name="PhieuNhap">
      <Column Name="MaPhieu" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="PhieuNhap_CTPN_TB" Member="CTPN_TBs" ThisKey="MaPhieu" OtherKey="MaPhieu" Type="CTPN_TB" />
      <Association Name="PhieuNhap_CTPN_TP" Member="CTPN_TPs" ThisKey="MaPhieu" OtherKey="MaPhieu" Type="CTPN_TP" />
      <Association Name="NhaCungCap_PhieuNhap" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="NhanVien_PhieuNhap" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="Username" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="NhanVien_TaiKhoan" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
      <Association Name="VaiTro_TaiKhoan" Member="VaiTro" ThisKey="Role" OtherKey="MaVaiTro" Type="VaiTro" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TKB" Member="TKBs">
    <Type Name="TKB">
      <Column Name="MaLich" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLam" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChamCong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LichLamViec_TKB" Member="LichLamViec" ThisKey="MaLich" OtherKey="MaLich" Type="LichLamViec" IsForeignKey="true" />
      <Association Name="NhanVien_TKB" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThietBi" Member="ThietBis">
    <Type Name="ThietBi">
      <Column Name="MaTB" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ThietBi_CT_TroChoi" Member="CT_TroChois" ThisKey="MaTB" OtherKey="MaTB" Type="CT_TroChoi" />
    </Type>
  </Table>
  <Table Name="dbo.ThucPham" Member="ThucPhams">
    <Type Name="ThucPham">
      <Column Name="MaTP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="ThucPham_Ve_TP" Member="Ve_TPs" ThisKey="MaTP" OtherKey="MaTP" Type="Ve_TP" />
      <Association Name="ThucPham_CTHD_TP" Member="CTHD_TPs" ThisKey="MaTP" OtherKey="MaTP" Type="CTHD_TP" />
      <Association Name="LoaiTP_ThucPham" Member="LoaiTP" ThisKey="MaLoai" OtherKey="MaLoai" Type="LoaiTP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TroChoi" Member="TroChois">
    <Type Name="TroChoi">
      <Column Name="MaTC" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiTroChoi" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TroChoi_CT_TroChoi" Member="CT_TroChois" ThisKey="MaTC" OtherKey="MaTC" Type="CT_TroChoi" />
      <Association Name="TroChoi_Ve" Member="Ves" ThisKey="MaTC" OtherKey="TroChoi" Type="Ve" />
      <Association Name="LoaiTC_TroChoi" Member="LoaiTC" ThisKey="LoaiTroChoi" OtherKey="MaLoai" Type="LoaiTC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VaiTro" Member="VaiTros">
    <Type Name="VaiTro">
      <Column Name="MaVaiTro" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenVaiTro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="VaiTro_PhanQuyen" Member="PhanQuyens" ThisKey="MaVaiTro" OtherKey="MaVaiTro" Type="PhanQuyen" />
      <Association Name="VaiTro_TaiKhoan" Member="TaiKhoans" ThisKey="MaVaiTro" OtherKey="Role" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.Ve" Member="Ves">
    <Type Name="Ve">
      <Column Name="MaVe" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoaiVe" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ThoiGianBan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TroChoi" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Ve_CTHD_Ve" Member="CTHD_Ves" ThisKey="MaVe" OtherKey="MaVe" Type="CTHD_Ve" />
      <Association Name="LoaiVe_Ve" Member="LoaiVe1" ThisKey="LoaiVe" OtherKey="MaLoai" Type="LoaiVe" IsForeignKey="true" />
      <Association Name="TroChoi_Ve" Member="TroChoi1" ThisKey="TroChoi" OtherKey="MaTC" Type="TroChoi" IsForeignKey="true" />
    </Type>
  </Table>
</Database>